/**
 * Regenerates docs/TOOLS.md from the registry so the catalogue can never drift
 * from the code. Run with: npx tsx scripts/gen-tools-doc.ts
 */
import { writeFileSync } from 'node:fs';
import { ALL_TOOLS, CATEGORIES, TOTAL_TOOLS, quickTools } from '../src/tools/registry.js';

const esc = (s: string): string => s.replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim();

const out: string[] = [
  '<!-- Generated by scripts/gen-tools-doc.ts — do not edit by hand. -->',
  '',
  '# Tool reference',
  '',
  `**${TOTAL_TOOLS} tools** across ${CATEGORIES.length} categories, plus a virtual ⚡ Quick Tools ` +
    `screen that surfaces the ${quickTools().length} most-used ones.`,
  '',
  '| Flag | Meaning |',
  '|---|---|',
  '| ⚡ | Listed under Quick Tools |',
  '| 🌐 | Makes an outbound network request (stricter rate limit) |',
  '| ⌨️ | Requires input; the bot waits for your next message |',
  '',
  '## Contents',
  '',
  ...CATEGORIES.map((c) => `- [${c.icon} ${c.title.en}](#${c.title.en.toLowerCase().replace(/[^a-z]+/g, '-')})`),
  `- [⚡ Quick Tools](#quick-tools)`,
  '',
];

for (const category of CATEGORIES) {
  const list = ALL_TOOLS.filter((t) => t.category === category.id);
  out.push(`## ${category.title.en} ${category.icon}`, '');
  out.push(`*${esc(category.description.en)}* — ${list.length} tools.`, '');

  for (const tool of list) {
    const flags = [tool.quick ? '⚡' : '', tool.network ? '🌐' : '', tool.needsInput ? '⌨️' : ''].filter(Boolean).join(' ');
    out.push(`### \`${tool.id}\` — ${tool.title.en} ${flags}`.trimEnd(), '');
    out.push(`**فارسی:** ${esc(tool.title.fa)} — ${esc(tool.description.fa)}`, '');
    out.push(esc(tool.description.en), '');
    out.push(`**Usage.** ${esc(tool.usage.en)}`, '');
    // `example` is a bilingual free-text block, not an {input, output} pair.
    out.push('**Example**', '', '```', tool.example.en.trim() || '(no input required)', '```', '');
    if (tool.file) {
      out.push(
        `**Input.** Upload a document (max ${Math.round(tool.file.maxBytes / (1024 * 1024))} MB)` +
          `${tool.file.pair ? ', two files one after the other' : ''}.`,
        '',
      );
    }
    out.push(`**Limitations.** ${esc(tool.limitations.en)}`, '');
  }
}

out.push('## Quick Tools', '');
out.push('The ⚡ Quick Tools screen is not a separate category — it is a shortcut list built from the', '');
out.push('`quick` flag, so a tool appears both in its own category and here:', '');
out.push(quickTools().map((t) => `\`${t.id}\``).join(' · '), '');
out.push('---', '', 'Regenerate with `npx tsx scripts/gen-tools-doc.ts`.', '');
writeFileSync(new URL('../docs/TOOLS.md', import.meta.url), out.join('\n'));
console.log(`docs/TOOLS.md written — ${TOTAL_TOOLS} tools`);
